#!/usr/bin/expect -f
# Author: Long Zhu <kyo2011@163.com>
#         Joshua Chen <iesugrace@gmail.com>
# Date: 2015-11-27
# Location: Shenzhen
# Desc: auto feed scp with password, push files to remote host

set timeout 30
set host [lindex $argv 0]
set port [lindex $argv 1]
set user [lindex $argv 2]
set pass [lindex $argv 3]
set last [expr $argc - 1]
set dst  [lindex $argv $last]
set options "StrictHostKeyChecking=no"

##
# delete other options, leave the source paths
# remove the dst
set srcs [lreplace $argv $last $last]
# remove all login options before
set srcs [lreplace $srcs 0 3]

spawn scp -r -P $port -o $options {*}$srcs $user@$host:$dst
expect {
    "*yes/no*" {send "yes\r"; exp_continue}
    "*password:" {send "${pass}\r"}
}
expect eof

# return the return code of the spawned process
lassign [wait] pid spawnid os_error_flag return_status
exit $return_status
