#!/usr/bin/expect -f
# Author: Long Zhu <kyo2011@163.com>
#         Joshua Chen <iesugrace@gmail.com>
# Date: 2016-02-14
# Location: Zhuhai
# Desc: auto feed scp with password,
# pull a single file from remote host

set timeout 30
set host [lindex $argv 0]
set port [lindex $argv 1]
set user [lindex $argv 2]
set pass [lindex $argv 3]
set src  [lindex $argv 4]
set dst  [lindex $argv 5]
set options "StrictHostKeyChecking=no"

spawn scp -r -P $port -o $options $user@$host:$src $dst
expect {
    "*yes/no*" {send "yes\r"; exp_continue}
    "*password:" {send "${pass}\r"}
}
expect eof

# return the return code of the spawned process
lassign [wait] pid spawnid os_error_flag return_status
exit $return_status
