#!/usr/bin/expect -f
# Author: Long Zhu <kyo2011@163.com>
#         Joshua Chen <iesugrace@gmail.com>
# Date: 2015-11-27
# Location: Shenzhen
# Desc: auto feed ssh with password, give a shell to the user

set host [lindex $argv 0]
set port [lindex $argv 1]
set user [lindex $argv 2]
set pass [lindex $argv 3]

spawn ssh -p $port $user@$host
expect {
    "*yes/no*" {send "yes\r"; exp_continue}
    "*password:" {send "${pass}\r"}
}
interact

# return the return code of the spawned process
lassign [wait] pid spawnid os_error_flag return_status
exit $return_status
