#!/bin/bash

help() {
    cat << EOF
Usage: $(basename $0) server-list cmd
       $(basename $0) server-list -f script
EOF
}

argparse() {
    if test $# -eq 2; then
        server_list=$1
        cmd=$2
    elif test $# -eq 3; then
        server_list=$1
        if test "$2" = "-f"; then
            script=$3
        else
            help >&2
            exit 1
        fi
    else
        help >&2
        exit 1
    fi
}

# upload script to the remote host
upload_file() {
    local user host port src dst options
    user=$1
    host=$2
    port=$3
    src=$4
    dst=$5
    options="UserKnownHostsFile=/dev/null"
    scp -P $port -o $options "$src" ${user}@${host}:"$dst"
}

# run a command on the remote server
run_cmd() {
    local user host port cmd options
    user=$1
    host=$2
    port=$3
    cmd=$4
    options="UserKnownHostsFile=/dev/null"
    ssh -p $port -o $options ${user}@${host} "$cmd"
}

port=9089
user=root



# list format
# ip password
