#!/bin/bash

help() {
    cat << EOF
Usage: $(basename $0) server-list cmd
       $(basename $0) server-list -f script
EOF
}

argparse() {
    if test $# -eq 2; then
        server_list=$1
        cmd=$2
    elif test $# -eq 3; then
        server_list=$1
        if test "$2" = "-f"; then
            script=$3
        else
            help >&2
            exit 1
        fi
    else
        help >&2
        exit 1
    fi
}

port=9089
user=root

ssh ${user}@$server


# list format
# ip password

# serverrun server-list cmdstring
# serverrun server-list -f script
